# Generated by Django 3.2 on 2021-04-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordering',
            old_name='books_in_order',
            new_name='books_number',
        ),
    ]
