# Generated by Django 3.2 on 2021-04-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_in_order_ordering_books_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordering',
            old_name='books_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='books.Ordering', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_in_order', to='books.book'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_has_books', to='books.order'),
        ),
    ]
