# Generated by Django 3.2 on 2021-04-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210413_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', through='books.Ordering', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.order'),
        ),
    ]
