# Generated by Django 3.2 on 2021-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210430_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=255, null=True),
        ),
    ]
