# Generated by Django 3.2 on 2021-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
