export const LOAD_ORDERS = "LOAD_ORDERS"
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS"
export const LOAD_ORDERS_ERROR = "LOAD_ORDERS_ERROR"

export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR"

export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"

export const ADD_ORDER = "ADD_ORDER"
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS"
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR"

export const EMPTY_ORDERS = "EMPTY_ORDERS"